<a href="https://colab.research.google.com/github/gb195966/ai_python/blob/main/pandas_pandas_loc_iloc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Estrutura de repeticao "for"

In [1]:

dict_desafio = [
    {"nome":"Maria Silva", "media":8.9},
    {"nome":"Joao Silva", "media":7.5},
    {"nome":"Ana Oliveira", "media":4.2},
    {"nome":"Pedro Costa", "media":1.4}
]

In [2]:
n = 0

while n < len(dict_desafio):
  print(dict_desafio)
  n +=1

[{'nome': 'Maria Silva', 'media': 8.9}, {'nome': 'Joao Silva', 'media': 7.5}, {'nome': 'Ana Oliveira', 'media': 4.2}, {'nome': 'Pedro Costa', 'media': 1.4}]
[{'nome': 'Maria Silva', 'media': 8.9}, {'nome': 'Joao Silva', 'media': 7.5}, {'nome': 'Ana Oliveira', 'media': 4.2}, {'nome': 'Pedro Costa', 'media': 1.4}]
[{'nome': 'Maria Silva', 'media': 8.9}, {'nome': 'Joao Silva', 'media': 7.5}, {'nome': 'Ana Oliveira', 'media': 4.2}, {'nome': 'Pedro Costa', 'media': 1.4}]
[{'nome': 'Maria Silva', 'media': 8.9}, {'nome': 'Joao Silva', 'media': 7.5}, {'nome': 'Ana Oliveira', 'media': 4.2}, {'nome': 'Pedro Costa', 'media': 1.4}]

In [3]:
for elemento in dict_desafio:
  print(elemento)

{'nome': 'Maria Silva', 'media': 8.9}
{'nome': 'Joao Silva', 'media': 7.5}
{'nome': 'Ana Oliveira', 'media': 4.2}
{'nome': 'Pedro Costa', 'media': 1.4}

In [4]:
for qualquer_nome in dict_desafio:
  print(qualquer_nome)

{'nome': 'Maria Silva', 'media': 8.9}
{'nome': 'Joao Silva', 'media': 7.5}
{'nome': 'Ana Oliveira', 'media': 4.2}
{'nome': 'Pedro Costa', 'media': 1.4}

In [5]:
for n in range(5):
  print(n)

0
1
2
3
4

In [7]:
for n in range(2,7,3):
  print(n)

2
5

In [8]:
pessoa = {
    "nome": "Fabricio",
    "idade": 19,
    "altura": 1.87
}
print(pessoa)

{'nome': 'Fabricio', 'idade': 19, 'altura': 1.87}

In [11]:
for chave in pessoa.items():
  print(chave)

('nome', 'Fabricio')
('idade', 19)
('altura', 1.87)

In [14]:
for chave,valor in pessoa.items():
  print(f"Achave é {chave} e o valor é {valor} .")

Achave é nome e o valor é Fabricio .
Achave é idade e o valor é 19 .
Achave é altura e o valor é 1.87 .

In [15]:
for n in range(11):
  if n%2 ==0:
    print(n)

0
2
4
6
8
10

In [16]:
for n in range(11):
  if n%3 ==0:
    print(n)

0
3
6
9

In [49]:
texto1 = "Fabricio CarRAro da alura"
texto2 = "marIA  aNA   Santos pereiRA"
texto3 = "PeDRO   alvaRes  cabrAl"
texto4 = "anA  carolINA   FerreirA"
texto5 = "robertO  carlos     Oliveira"

In [52]:
def escreve_texto_corretamente(texto):
 texto_novo = texto.strip().upper()
 lista_de_palavras = texto_novo.split()
 nome_final = " ".join(lista_de_palavras)
 return nome_final

In [28]:
escreve_texto_corretamente(texto1)

FABRICIO CARRARO DA ALURA

In [29]:
escreve_texto_corretamente(texto2)

MARIA ANA SANTOS PEREIRA

In [36]:
def escreve_texto_corretamente_alternativa(texto):
 print(" ".join(texto.upper().split()))

In [37]:
escreve_texto_corretamente_alternativa(texto1)

FABRICIO CARRARO DA ALURA

In [39]:
salas_de_aula = ["Sala 1","Sala 2","Sala 3"]

In [50]:
import random

def aloca_alunos_em_salas(nome_do_aluno, lista_de_salas):
  sala_do_aluno = random.choice(lista_de_salas)
  dict_aluno = {
    "nome": nome_do_aluno,
    "sala": sala_do_aluno
  }

  print(dict_aluno)

In [51]:
aloca_alunos_em_salas(texto1,salas_de_aula)

{'nome': 'Fabricio CarRAro da alura', 'sala': 'Sala 1'}

In [53]:
nome_final = escreve_texto_corretamente(texto1)

In [54]:
aloca_alunos_em_salas(texto1,salas_de_aula)

{'nome': 'Fabricio CarRAro da alura', 'sala': 'Sala 1'}

In [55]:
aloca_alunos_em_salas(nome_final,salas_de_aula)

{'nome': 'FABRICIO CARRARO DA ALURA', 'sala': 'Sala 3'}

Desafio:
<br>
1. Pedir para uma IA gerar em python uma lista de 20 emails para voce.
2. Criar uma funcao que vai receber como argumento/parametro essa lista de emails, percorrer essa lista de emails, e, para cada email da lista, ela irá chamar a IA fo Gemini via API e pedir para ela resumir para voce todos os emails em apenas 1 linha, definindo o que essa pessoa queria no email

In [5]:
email_bodies = [
    "Olá equipe, gostaria de agendar uma reunião para alinharmos as próximas entregas do projeto.",
    "Gostaria de solicitar minhas férias para o período entre 10 e 20 de julho.",
    "Identificamos uma instabilidade no sistema de pagamentos durante a madrugada.",
    "Você está convidado para participar do nosso evento anual de tecnologia.",
    "Realizamos uma atualização nos servidores para melhorar a performance da aplicação.",
    "Agradecemos sua participação no processo seletivo. Em breve retornaremos com novidades.",
    "Seu pagamento foi processado com sucesso e já consta em nosso sistema.",
    "Por motivos de segurança, recomendamos a alteração da sua senha imediatamente.",
    "Segue em anexo o relatório consolidado referente ao último trimestre.",
    "Todos os colaboradores devem concluir o treinamento até sexta-feira.",
    "Gostaríamos de discutir oportunidades de parceria entre nossas empresas.",
    "O sistema ficará indisponível neste domingo das 02h às 05h para manutenção.",
    "Seja bem-vindo à empresa! Estamos felizes em ter você conosco.",
    "Precisamos revisar algumas cláusulas do contrato vigente.",
    "Sua opinião é muito importante. Responda nossa pesquisa de satisfação.",
    "Temos o prazer de anunciar o lançamento do nosso novo produto.",
    "Detectamos um erro na integração com o serviço externo e já estamos atuando.",
    "O orçamento enviado foi aprovado pela diretoria financeira.",
    "Recebemos uma solicitação de recuperação de acesso à sua conta.",
    "Seu chamado foi resolvido e será encerrado automaticamente em 48 horas."
]

print(email_bodies)

['Olá equipe, gostaria de agendar uma reunião para alinharmos as próximas entregas do projeto.', 'Gostaria de solicitar minhas férias para o período entre 10 e 20 de julho.', 'Identificamos uma instabilidade no sistema de pagamentos durante a madrugada.', 'Você está convidado para participar do nosso evento anual de tecnologia.', 'Realizamos uma atualização nos servidores para melhorar a performance da aplicação.', 'Agradecemos sua participação no processo seletivo. Em breve retornaremos com novidades.', 'Seu pagamento foi processado com sucesso e já consta em nosso sistema.', 'Por motivos de segurança, recomendamos a alteração da sua senha imediatamente.', 'Segue em anexo o relatório consolidado referente ao último trimestre.', 'Todos os colaboradores devem concluir o treinamento até sexta-feira.', 'Gostaríamos de discutir oportunidades de parceria entre nossas empresas.', 'O sistema ficará indisponível neste domingo das 02h às 05h para manutenção.', 'Seja bem-vindo à empresa! Estamos felizes em ter você conosco.', 'Precisamos revisar algumas cláusulas do contrato vigente.', 'Sua opinião é muito importante. Responda nossa pesquisa de satisfação.', 'Temos o prazer de anunciar o lançamento do nosso novo produto.', 'Detectamos um erro na integração com o serviço externo e já estamos atuando.', 'O orçamento enviado foi aprovado pela diretoria financeira.', 'Recebemos uma solicitação de recuperação de acesso à sua conta.', 'Seu chamado foi resolvido e será encerrado automaticamente em 48 horas.']

In [63]:
import os
from google.colab import userdata

from google import genai
client = genai.Client()


os.environ["GOOGLE_API_KEY"] = userdata.get('GEMINI_API_KEY')

def resumidor_de_emails(lista_de_emails):
  for numero,email in enumerate(lista_de_emails):
    resposta = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=f"""Vou te mandar o corpo de um e-mail. Quero que voce o resuma em apenas 1 linha,
        "passando o intuito daquele e-mail. Segue o e-mail: {email}"""
        )
    print(f"Email{numero}: {resposta.text}")
    print("-" * 50)

In [ ]:
resumidor_de_emails(email_bodies)

In [75]:
!pip install -q groq

# Groq

In [12]:
os.environ["GROQ_API_KEY"] = userdata.get('GROOQ_API_KEY')

In [78]:
from groq import Groq

client = Groq()
completion = client.chat.completions.create(
    model="openai/gpt-oss-20b",
    messages=[
      {
        "role": "user",
        "content": "De que é feito o Sol?"
      }
    ],
    temperature=1, #0 - menos criativo possivel; 2- o mais criativo possivel
    max_completion_tokens=7000,
    top_p=1,
    reasoning_effort="medium",
    stream=True,
    stop=None
)

for chunk in completion:
    print(chunk.choices[0].delta.content or "", end="")

O Sol não é um objeto sólido, mas sim uma enorme esfera de plasma – matéria extremamente quente e ionizada. Sua composição química (massa total) é bem conhecida graças à espectroscopia, à helioseismologia e a modelos de evolução estelar. Em resumo:

| Elemento | Porcentagem (massa) |
|----------|---------------------|
| Hidrogênio | ~ 73 % |
| Hélio | ~ 25 % |
| Elementos mais pesados (metais) | ~ 2 % |

### O que isso significa na prática?

1. **Hidrogênio**
   - É a substância dominante e a fonte de energia do Sol.
   - Em temperaturas de cerca de 15 milhões de graus Celsius, os prótons (núcleos de hidrogênio) são ionizados (perdem seus elétrons) e formam um plasma.
   - Por meio da fusão nuclear (principalmente o ciclo próton‑próton), dois prótons se combinam, passando por etapas intermediárias, para formar hélio e liberar enormes quantidades de energia (em forma de radiação, partículas e calor).

2. **Hélio**
   - Resultado direto da fusão de hidrogênio.
   - Também permanece ionizado em praticamente todo o interior do Sol, mas em menor grau de ionização que o hidrogênio devido à sua massa maior.

3. **Metais (ou elementos mais pesados)**
   - Embora representem apenas cerca de 2 % da massa, são importantes para a estrutura e evolução do Sol.
   - Contribuem para a opacidade do plasma, influenciando como a energia se move do núcleo até a superfície.

### Estrutura do Sol

| Região | Características |
|--------|-----------------|
| **Núcleo** | Onde ocorre a fusão; temperatura ~ 15 milhões K; densidade alta (~ 150 kg/m³). |
| **Zona Radiativa** | Energia transportada principalmente por radiação; tempo de migração de energia é de milhões de anos. |
| **Zona Convectiva** | Transferência de energia por convecção (movimento de massas de plasma); tem a forma de "turbilhões" de plasma que ascendem e descem. |
| **Fotosfera** | Camada visível que vemos como a superfície solar; temperatura ~ 5 500 K. |
| **Cromosfera e Coroa** | Camadas superiores, muito mais esparsas, onde a temperatura sobe novamente (até milhões de graus na coroa). |

### Por que o Sol parece "brilhar" tão intensamente?

- A fusão nuclear no núcleo converte uma pequena fração da massa do Sol em energia de acordo com a equação \(E=mc^2\).
- A energia produzida (cerca de \(3,8 \times 10^{26}\) W) escapa do interior em forma de radiação eletromagnética (principalmente luz visível e infravermelha), partículas solares e calor que mantêm a Terra aquecida.

**Em resumo:** o Sol é composto majoritariamente por hidrogênio e hélio em forma de plasma, com uma pequena quantidade de elementos mais pesados. Essa composição, juntamente com as condições extremas de temperatura e pressão, permite a fusão nuclear que gera a enorme energia que alimenta o nosso sistema solar.

In [13]:
!pip install -q groq

In [15]:
from groq import Groq
client = Groq()
os.environ["GROOQ_API_KEY"] = userdata.get('GROOQ_API_KEY')

GroqError: The api_key client option must be set either by passing api_key to the client or by setting the GROQ_API_KEY environment variable

In [35]:
def resumidor_de_emails(lista_de_emails):

  lista_de_resumos = []
  for numero,email in enumerate(lista_de_emails):
    resposta = client.chat.completions.create(
    model="openai/gpt-oss-20b",
    messages=[
      {
        "role": "user",
        "content":f"""Vou te mandar o corpo de um e-mail. Quero que voce o resuma em apenas 1 linha,
        passando o intuito daquele e-mail. Segue o e-mail: {email}"""
      }
    ],
    temperature=1, #0 - menos criativo possivel; 2- o mais criativo possivel
    max_completion_tokens=7000,
    top_p=1,
    reasoning_effort="medium",
    stream=False, # Alterado para False
    stop=None
)
    # Acessa o conteúdo da resposta de forma não-streaming
    summary_content = resposta.choices[0].message.content
    print(f"Email{numero}: {summary_content}")
    lista_de_resumos.append(f"Email{numero}: {summary_content}")
    print("-" * 50)
  return lista_de_resumos

In [36]:
lista_resumos = resumidor_de_emails(email_bodies)

Email0: Solicita agendar reunião para alinhar as próximas entregas do projeto.
--------------------------------------------------
Email1: Solicitação de férias de 10 a 20 de julho.
--------------------------------------------------
Email2: Notificar instabilidade no sistema de pagamentos ocorrida na madrugada.
--------------------------------------------------
Email3: Convite para participar do evento anual de tecnologia.
--------------------------------------------------
Email4: Atualizamos os servidores para melhorar a performance da aplicação.
--------------------------------------------------
Email5: Agradecemos sua participação no processo seletivo e informaremos novidades em breve.
--------------------------------------------------
Email6: Pagamento processado com sucesso e registrado no sistema.
--------------------------------------------------
Email7: Alerta de segurança pedindo a imediata troca de senha.
--------------------------------------------------
Email8: Anexo o relatório consolidado referente ao último trimestre.
--------------------------------------------------
Email9: Lembrete para que todos os colaboradores concluam o treinamento até a próxima sexta-feira.
--------------------------------------------------
Email10: Solicitação para discutir oportunidades de parceria entre nossas empresas.
--------------------------------------------------
Email11: Manutenção programada: sistema indisponível este domingo das 02h às 05h.
--------------------------------------------------
Email12: Bem-vindo à empresa: estamos felizes em tê-lo conosco.
--------------------------------------------------
Email13: Solicita revisão de cláusulas do contrato vigente.
--------------------------------------------------
Email14: Peça ao destinatário para responder à pesquisa de satisfação, salientando a importância da opinião dele.
--------------------------------------------------
Email15: Anunciar o lançamento do nosso novo produto.
--------------------------------------------------
Email16: Informamos que detectamos um erro na integração com o serviço externo e já estamos correndo a solução.
--------------------------------------------------
Email17: Informar que o orçamento enviado foi aprovado pela diretoria financeira.
--------------------------------------------------
Email18: Solicitação de recuperação de acesso à sua conta.
--------------------------------------------------
Email19: Seu chamado foi resolvido e será encerrado automaticamente em 48 horas.
--------------------------------------------------

# Lendo e escrevendo arquivos usando Python

In [38]:
with open("lista-de-resumos.txt", "w", encoding="utf-8") as arquivo:
  for resumo in lista_resumos:
    arquivo.write(resumo + "\n")

In [44]:
nova_lista_de_leitura=[]
with open("lista-de-resumos.txt", "r", encoding="utf-8") as arquivo:
  for linha in arquivo:
    nova_lista_de_leitura.append(linha.strip())

In [45]:
nova_lista_de_leitura

['Email0: Solicita agendar reunião para alinhar as próximas entregas do projeto.',
 'Email1: Solicitação de férias de 10 a 20 de julho.',
 'Email2: Notificar instabilidade no sistema de pagamentos ocorrida na madrugada.',
 'Email3: Convite para participar do evento anual de tecnologia.',
 'Email4: Atualizamos os servidores para melhorar a performance da aplicação.',
 'Email5: Agradecemos sua participação no processo seletivo e informaremos novidades em breve.',
 'Email6: Pagamento processado com sucesso e registrado no sistema.',
 'Email7: Alerta de segurança pedindo a imediata troca de senha.',
 'Email8: Anexo o relatório consolidado referente ao último trimestre.',
 'Email9: Lembrete para que todos os colaboradores concluam o treinamento até a próxima sexta-feira.',
 'Email10: Solicitação para discutir oportunidades de parceria entre nossas empresas.',
 'Email11: Manutenção programada: sistema indisponível este domingo das 02h às 05h.',
 'Email12: Bem-vindo à empresa: estamos felizes em tê-lo conosco.',
 'Email13: Solicita revisão de cláusulas do contrato vigente.',
 'Email14: Peça ao destinatário para responder à pesquisa de satisfação, salientando a importância da opinião dele.',
 'Email15: Anunciar o lançamento do nosso novo produto.',
 'Email16: Informamos que detectamos um erro na integração com o serviço externo e já estamos correndo a solução.',
 'Email17: Informar que o orçamento enviado foi aprovado pela diretoria financeira.',
 'Email18: Solicitação de recuperação de acesso à sua conta.',
 'Email19: Seu chamado foi resolvido e será encerrado automaticamente em 48\u202fhoras.']

In [42]:
conteudo = ""
with open("lista-de-resumos.txt", "r", encoding="utf-8") as arquivo:
  conteudo = arquivo.read()

In [46]:
conteudo

'Email0: Solicita agendar reunião para alinhar as próximas entregas do projeto.\nEmail1: Solicitação de férias de 10 a 20 de julho.\nEmail2: Notificar instabilidade no sistema de pagamentos ocorrida na madrugada.\nEmail3: Convite para participar do evento anual de tecnologia.\nEmail4: Atualizamos os servidores para melhorar a performance da aplicação.\nEmail5: Agradecemos sua participação no processo seletivo e informaremos novidades em breve.\nEmail6: Pagamento processado com sucesso e registrado no sistema.\nEmail7: Alerta de segurança pedindo a imediata troca de senha.\nEmail8: Anexo o relatório consolidado referente ao último trimestre.\nEmail9: Lembrete para que todos os colaboradores concluam o treinamento até a próxima sexta-feira.\nEmail10: Solicitação para discutir oportunidades de parceria entre nossas empresas.\nEmail11: Manutenção programada: sistema indisponível este domingo das 02h às 05h.\nEmail12: Bem-vindo à empresa: estamos felizes em tê-lo conosco.\nEmail13: Solicita revisão de cláusulas do contrato vigente.\nEmail14: Peça ao destinatário para responder à pesquisa de satisfação, salientando a importância da opinião dele.\nEmail15: Anunciar o lançamento do nosso novo produto.\nEmail16: Informamos que detectamos um erro na integração com o serviço externo e já estamos correndo a solução.\nEmail17: Informar que o orçamento enviado foi aprovado pela diretoria financeira.\nEmail18: Solicitação de recuperação de acesso à sua conta.\nEmail19: Seu chamado foi resolvido e será encerrado automaticamente em 48\u202fhoras.\n'

In [47]:
nova_lista_de_leitura_2 = []
with open("lista-de-resumos.txt", "r", encoding="utf-8") as arquivo:
  nova_lista_de_leitura_2 = arquivo.readlines()

In [48]:
nova_lista_de_leitura_2

['Email0: Solicita agendar reunião para alinhar as próximas entregas do projeto.\n',
 'Email1: Solicitação de férias de 10 a 20 de julho.\n',
 'Email2: Notificar instabilidade no sistema de pagamentos ocorrida na madrugada.\n',
 'Email3: Convite para participar do evento anual de tecnologia.\n',
 'Email4: Atualizamos os servidores para melhorar a performance da aplicação.\n',
 'Email5: Agradecemos sua participação no processo seletivo e informaremos novidades em breve.\n',
 'Email6: Pagamento processado com sucesso e registrado no sistema.\n',
 'Email7: Alerta de segurança pedindo a imediata troca de senha.\n',
 'Email8: Anexo o relatório consolidado referente ao último trimestre.\n',
 'Email9: Lembrete para que todos os colaboradores concluam o treinamento até a próxima sexta-feira.\n',
 'Email10: Solicitação para discutir oportunidades de parceria entre nossas empresas.\n',
 'Email11: Manutenção programada: sistema indisponível este domingo das 02h às 05h.\n',
 'Email12: Bem-vindo à empresa: estamos felizes em tê-lo conosco.\n',
 'Email13: Solicita revisão de cláusulas do contrato vigente.\n',
 'Email14: Peça ao destinatário para responder à pesquisa de satisfação, salientando a importância da opinião dele.\n',
 'Email15: Anunciar o lançamento do nosso novo produto.\n',
 'Email16: Informamos que detectamos um erro na integração com o serviço externo e já estamos correndo a solução.\n',
 'Email17: Informar que o orçamento enviado foi aprovado pela diretoria financeira.\n',
 'Email18: Solicitação de recuperação de acesso à sua conta.\n',
 'Email19: Seu chamado foi resolvido e será encerrado automaticamente em 48\u202fhoras.\n']

# Manipulando dados com Pandas

In [49]:
import pandas as pd

In [50]:
df = pd.read_csv("/meu_csv.csv")

In [51]:
df

       nome  media
0       Ana    7.5
1    Carlos    8.2
2   Beatriz    9.1
3     Diogo    6.8
4   Eduarda    5.9
5  Fernanda    8.5
6   Gustavo    7.3
7    Helena    9.5
8      Igor    6.1
9   Juliana    8.9

In [52]:
df.head(7)

       nome  media
0       Ana    7.5
1    Carlos    8.2
2   Beatriz    9.1
3     Diogo    6.8
4   Eduarda    5.9
5  Fernanda    8.5
6   Gustavo    7.3

In [53]:
df.tail()

       nome  media
5  Fernanda    8.5
6   Gustavo    7.3
7    Helena    9.5
8      Igor    6.1
9   Juliana    8.9

# Desafio:
<br>
1.Criar um arquivo .txt a partir de uma lista de perguntas vindas de uma lista em Python.<br>
2.Ler essas perguntas desse arquivo .txt<br>
3.Salvar os resultados em um novo arquivo .csv<br>
5.Ler o arquivo .csv usando pandas

In [31]:
#Etapa 1
lista_de_perguntas = [
    "De que é feito o Sol?",
    "De que é feito o planeta Saturno?",
    "Qual é a galaxia mais aintga ja encontrada?",
    "Qual é a maior estrela já encontrada?",
    "Qual é a estrela mais próxima do Sol?",
    "De que é feito o planeta Vênus?",
    "De que é feito o planeta Terra?",
    "De que é feito o planeta Júpiter?",
    "De que é feito o planeta Mercúrio?",
    "De que é feito o planeta Plutão?"
]

with open("perguntas.txt", "w", encoding="utf-8") as arquivo:
  for pergunta in lista_de_perguntas:
    arquivo.write(pergunta + "\n")

In [32]:
#Etapa 2
lista_desafio = []
with open("perguntas.txt", "r", encoding="utf-8") as arquivo:
  for linha in arquivo:
    lista_desafio.append(linha.strip())
print(lista_desafio)

['De que é feito o Sol?', 'De que é feito o planeta Saturno?', 'Qual é a galaxia mais aintga ja encontrada?', 'Qual é a maior estrela já encontrada?', 'Qual é a estrela mais próxima do Sol?', 'De que é feito o planeta Vênus?', 'De que é feito o planeta Terra?', 'De que é feito o planeta Júpiter?', 'De que é feito o planeta Mercúrio?', 'De que é feito o planeta Plutão?']

In [17]:
!pip install -q groq

In [33]:
#Etapa 3
import os
from google.colab import userdata

# Correctly set the environment variable GROQ_API_KEY before initializing the client
os.environ["GROQ_API_KEY"] = userdata.get('GROQ_API_KEY') # Assuming the secret in Colab is named 'GROQ_API_KEY'

from groq import Groq
client = Groq()

lista_de_dicionarios_de_resposta = []
for pergunta in lista_desafio:
    resposta = client.chat.completions.create(
    model="openai/gpt-oss-20b",
    messages=[
      {
        "role": "user",
        "content":f"""Gere uma resposta muito sucinta para a pergunta: {pergunta}"""
      }
    ],
    temperature=1,
    max_completion_tokens=7000,
    top_p=1,
    reasoning_effort="medium",
    stream=False,
    stop=None
  )
    # The line below was dead code and has been removed.
    lista_de_dicionarios_de_resposta.append({"pergunta":pergunta, "resposta":resposta.choices[0].message.content})

In [34]:
lista_de_dicionarios_de_resposta

[{'pergunta': 'De que é feito o Sol?',
  'resposta': 'O Sol é composto principalmente de hidrogênio (~74\u202f%) e hélio (~24\u202f%), com traços de elementos mais pesados.'},
 {'pergunta': 'De que é feito o planeta Saturno?',
  'resposta': 'Saturno é um gigante gasoso composto principalmente de hidrogênio e hélio, com pequenas quantidades de metano, amônia, água e um núcleo rochoso/ice.'},
 {'pergunta': 'Qual é a galaxia mais aintga ja encontrada?',
  'resposta': 'A mais antiga galáxia já descoberta é a **GN‑z11**, localizada a ~13,4\u202fbilhões de anos de luz (redshift z\u202f≈\u202f11), quando o universo tinha apenas ~400\u202fmilhões de anos.'},
 {'pergunta': 'Qual é a maior estrela já encontrada?',
  'resposta': 'UY\u202fScuti, uma super‑gigante vermelha com diâmetro ≈\u202f1700\u202fvezes o do Sol.'},
 {'pergunta': 'Qual é a estrela mais próxima do Sol?',
  'resposta': 'Proxima\u202fCentauri.'},
 {'pergunta': 'De que é feito o planeta Vênus?',
  'resposta': 'Rocha e metal, com uma atmosfera densa de CO₂ e N₂.'},
 {'pergunta': 'De que é feito o planeta Terra?',
  'resposta': 'A Terra é composta por um núcleo metálico (ferro‑níquel), um manto de silício e oxigênio, uma crosta de rochas, água, gelo e uma atmosfera de gases.'},
 {'pergunta': 'De que é feito o planeta Júpiter?',
  'resposta': 'Júpiter é composto principalmente de hidrogênio e hélio, com traços de metano, amônia e água.'},
 {'pergunta': 'De que é feito o planeta Mercúrio?',
  'resposta': 'Mercúrio é composto principalmente de ferro, com um manto de silício e magnésio e uma crosta de rochas silicatadas.'},
 {'pergunta': 'De que é feito o planeta Plutão?',
  'resposta': 'Plutão é composto principalmente por rochas e gelo (água, metano e amônia) com uma camada interna de ferro e silício.'}]

In [39]:
#Etapa 4
with open("respostas1.csv", "w", encoding="utf-8") as arquivo:
  arquivo.write("pergunta,resposta\n")
  for pergunta_dict in lista_de_dicionarios_de_resposta:
    arquivo.write(f"{pergunta_dict['pergunta']},{pergunta_dict['resposta']}\n")

In [37]:
import pandas as pd
df_perguntas_e_respostas = pd.DataFrame(lista_de_dicionarios_de_resposta)

In [38]:
df_perguntas_e_respostas

,pergunta,resposta
0,De que é feito o Sol?,O Sol é composto principalmente de hidrogênio ...
1,De que é feito o planeta Saturno?,Saturno é um gigante gasoso composto principal...
2,Qual é a galaxia mais aintga ja encontrada?,A mais antiga galáxia já descoberta é a **GN‑z...
3,Qual é a maior estrela já encontrada?,"UY Scuti, uma super‑gigante vermelha com diâme..."
4,Qual é a estrela mais próxima do Sol?,Proxima Centauri.
5,De que é feito o planeta Vênus?,"Rocha e metal, com uma atmosfera densa de CO₂ ..."
6,De que é feito o planeta Terra?,A Terra é composta por um núcleo metálico (fer...
7,De que é feito o planeta Júpiter?,Júpiter é composto principalmente de hidrogêni...
8,De que é feito o planeta Mercúrio?,"Mercúrio é composto principalmente de ferro, c..."
9,De que é feito o planeta Plutão?,Plutão é composto principalmente por rochas e ...

In [40]:
df_perguntas_e_respostas.to_csv("respostas2.csv", index=False, encoding="utf-8")

In [41]:
# Etapa e
novo_df = pd.read_csv("respostas2.csv")

In [42]:
novo_df

,pergunta,resposta
0,De que é feito o Sol?,O Sol é composto principalmente de hidrogênio ...
1,De que é feito o planeta Saturno?,Saturno é um gigante gasoso composto principal...
2,Qual é a galaxia mais aintga ja encontrada?,A mais antiga galáxia já descoberta é a **GN‑z...
3,Qual é a maior estrela já encontrada?,"UY Scuti, uma super‑gigante vermelha com diâme..."
4,Qual é a estrela mais próxima do Sol?,Proxima Centauri.
5,De que é feito o planeta Vênus?,"Rocha e metal, com uma atmosfera densa de CO₂ ..."
6,De que é feito o planeta Terra?,A Terra é composta por um núcleo metálico (fer...
7,De que é feito o planeta Júpiter?,Júpiter é composto principalmente de hidrogêni...
8,De que é feito o planeta Mercúrio?,"Mercúrio é composto principalmente de ferro, c..."
9,De que é feito o planeta Plutão?,Plutão é composto principalmente por rochas e ...

In [44]:
novo_df.head()

,pergunta,resposta
0,De que é feito o Sol?,O Sol é composto principalmente de hidrogênio ...
1,De que é feito o planeta Saturno?,Saturno é um gigante gasoso composto principal...
2,Qual é a galaxia mais aintga ja encontrada?,A mais antiga galáxia já descoberta é a **GN‑z...
3,Qual é a maior estrela já encontrada?,"UY Scuti, uma super‑gigante vermelha com diâme..."
4,Qual é a estrela mais próxima do Sol?,Proxima Centauri.

In [46]:
import random
import pandas as pd

# Gerar 50 linhas de dados
num_rows = 50

# Listas para gerar dados aleatórios
nomes_produtos_base = ["Monitor", "Teclado", "Mouse", "Câmera", "Fone de Ouvido", "Tablet", "Smartwatch", "Carregador", "Caixa de Som", "Roteador", "Impressora", "Webcam", "Microfone", "Notebook", "Desktop"]
qualificadores_produtos = ["Gaming", "Bluetooth", "Sem Fio", "Ultra HD", "Profissional", "Compacto", "Ergonômico", "Básico", "Premium", "Portátil"]
categorias = ["Eletrônicos", "Informática", "Acessórios", "Áudio e Vídeo", "Periféricos", "Dispositivos Móveis"]

# Listas para armazenar os dados gerados
nome_do_produto = []
categoria_do_produto = []
preco_do_produto = []
quantos_itens_vendidos = []
avaliacao_do_produto = []

for _ in range(num_rows):
    # Nome do Produto
    nome_base = random.choice(nomes_produtos_base)
    qualificador = random.choice(qualificadores_produtos)
    nome_do_produto.append(f"{nome_base} {qualificador}")

    # Categoria do Produto
    categoria_do_produto.append(random.choice(categorias))

    # Preço do Produto (entre 10.00 e 1000.00)
    preco_do_produto.append(round(random.uniform(10.00, 1000.00), 2))

    # Quantos itens do produto foram vendidos (entre 10 e 500)
    quantos_itens_vendidos.append(random.randint(10, 500))

    # Avaliação do Produto (entre 1.0 e 5.0)
    avaliacao_do_produto.append(round(random.uniform(1.0, 5.0), 1))

# Criar o DataFrame
df_produtos = pd.DataFrame({
    'Nome do Produto': nome_do_produto,
    'Categoria do Produto': categoria_do_produto,
    'Preço do Produto': preco_do_produto,
    'Itens Vendidos': quantos_itens_vendidos,
    'Avaliação do Produto': avaliacao_do_produto
})

print(df_produtos.head())

         Nome do Produto Categoria do Produto  Preço do Produto  \
0  Carregador Ergonômico          Eletrônicos            729.33
1   Carregador Bluetooth          Eletrônicos            643.60
2      Roteador Ultra HD        Áudio e Vídeo            642.42
3    Caixa de Som Gaming        Áudio e Vídeo            260.88
4        Roteador Gaming          Periféricos            275.75

   Itens Vendidos  Avaliação do Produto
0             277                   2.7
1             272                   3.5
2             497                   2.8
3             356                   3.0
4              67                   1.1

In [47]:
df_produtos["Categoria do Produto"]

0             Eletrônicos
1             Eletrônicos
2           Áudio e Vídeo
3           Áudio e Vídeo
4             Periféricos
5             Eletrônicos
6             Eletrônicos
7     Dispositivos Móveis
8     Dispositivos Móveis
9             Informática
10             Acessórios
11            Eletrônicos
12             Acessórios
13            Eletrônicos
14            Eletrônicos
15          Áudio e Vídeo
16            Informática
17            Eletrônicos
18            Eletrônicos
19            Eletrônicos
20            Periféricos
21          Áudio e Vídeo
22          Áudio e Vídeo
23            Periféricos
24            Informática
25            Eletrônicos
26            Periféricos
27          Áudio e Vídeo
28            Periféricos
29            Eletrônicos
30          Áudio e Vídeo
31    Dispositivos Móveis
32             Acessórios
33            Informática
34            Eletrônicos
35            Eletrônicos
36          Áudio e Vídeo
37            Informática
38             Acessórios
39            Informática
40            Periféricos
41            Periféricos
42            Eletrônicos
43    Dispositivos Móveis
44            Periféricos
45             Acessórios
46            Eletrônicos
47    Dispositivos Móveis
48    Dispositivos Móveis
49    Dispositivos Móveis
Name: Categoria do Produto, dtype: object

In [48]:
df_produtos["Categoria do Produto"].unique()

array(['Eletrônicos', 'Áudio e Vídeo', 'Periféricos',
       'Dispositivos Móveis', 'Informática', 'Acessórios'], dtype=object)

In [49]:
set(df_produtos["Categoria do Produto"])

{'Acessórios',
 'Dispositivos Móveis',
 'Eletrônicos',
 'Informática',
 'Periféricos',
 'Áudio e Vídeo'}

# Filtrando elementos de um DataFrame Pandas

In [50]:
df_produtos["Categoria do Produto"] == "Eletrônicos"

0      True
1      True
2     False
3     False
4     False
5      True
6      True
7     False
8     False
9     False
10    False
11     True
12    False
13     True
14     True
15    False
16    False
17     True
18     True
19     True
20    False
21    False
22    False
23    False
24    False
25     True
26    False
27    False
28    False
29     True
30    False
31    False
32    False
33    False
34     True
35     True
36    False
37    False
38    False
39    False
40    False
41    False
42     True
43    False
44    False
45    False
46     True
47    False
48    False
49    False
Name: Categoria do Produto, dtype: bool

In [51]:
df_produtos[df_produtos["Categoria do Produto"] == "Eletrônicos"]

,Nome do Produto,Categoria do Produto,Preço do Produto,Itens Vendidos,Avaliação do Produto
0,Carregador Ergonômico,Eletrônicos,729.33,277,2.7
1,Carregador Bluetooth,Eletrônicos,643.60,272,3.5
5,Desktop Compacto,Eletrônicos,100.58,157,1.8
6,Câmera Gaming,Eletrônicos,816.84,303,1.5
11,Câmera Profissional,Eletrônicos,38.25,449,1.9
13,Carregador Profissional,Eletrônicos,758.30,81,3.3
14,Webcam Sem Fio,Eletrônicos,121.72,37,2.5
17,Câmera Gaming,Eletrônicos,995.41,242,2.2
18,Caixa de Som Premium,Eletrônicos,495.30,92,1.3
19,Caixa de Som Profissional,Eletrônicos,134.02,30,2.1
25,Caixa de Som Gaming,Eletrônicos,874.02,342,2.0
29,Monitor Sem Fio,Eletrônicos,541.71,110,3.5
34,Notebook Ergonômico,Eletrônicos,589.19,467,2.9
35,Tablet Ultra HD,Eletrônicos,355.71,252,2.3
42,Câmera Portátil,Eletrônicos,626.27,400,1.8
46,Carregador Ergonômico,Eletrônicos,655.46,243,1.3

In [52]:
df_produtos[df_produtos["Avaliação do Produto"] < 2.0]

,Nome do Produto,Categoria do Produto,Preço do Produto,Itens Vendidos,Avaliação do Produto
4,Roteador Gaming,Periféricos,275.75,67,1.1
5,Desktop Compacto,Eletrônicos,100.58,157,1.8
6,Câmera Gaming,Eletrônicos,816.84,303,1.5
7,Microfone Ergonômico,Dispositivos Móveis,71.11,363,1.3
11,Câmera Profissional,Eletrônicos,38.25,449,1.9
18,Caixa de Som Premium,Eletrônicos,495.30,92,1.3
23,Impressora Premium,Periféricos,437.98,70,1.5
26,Desktop Gaming,Periféricos,157.81,13,1.2
33,Caixa de Som Compacto,Informática,661.79,414,1.8
41,Desktop Bluetooth,Periféricos,670.30,397,1.1
42,Câmera Portátil,Eletrônicos,626.27,400,1.8
45,Webcam Portátil,Acessórios,724.34,104,1.1
46,Carregador Ergonômico,Eletrônicos,655.46,243,1.3
47,Fone de Ouvido Compacto,Dispositivos Móveis,847.99,163,1.3
48,Monitor Premium,Dispositivos Móveis,420.77,115,1.5

In [53]:
df_produtos.shape

(50, 5)

In [54]:
df_produtos_avaliacao_menor_que_2 = df_produtos[df_produtos["Avaliação do Produto"] < 2.0]

In [56]:
df_produtos_avaliacao_menor_que_2.shape

(15, 5)

In [57]:
df_produtos[(df_produtos["Categoria do Produto"] == "Eletrônicos") & (df_produtos["Preço do Produto"] >= 350.0)]

,Nome do Produto,Categoria do Produto,Preço do Produto,Itens Vendidos,Avaliação do Produto
0,Carregador Ergonômico,Eletrônicos,729.33,277,2.7
1,Carregador Bluetooth,Eletrônicos,643.60,272,3.5
6,Câmera Gaming,Eletrônicos,816.84,303,1.5
13,Carregador Profissional,Eletrônicos,758.30,81,3.3
17,Câmera Gaming,Eletrônicos,995.41,242,2.2
18,Caixa de Som Premium,Eletrônicos,495.30,92,1.3
25,Caixa de Som Gaming,Eletrônicos,874.02,342,2.0
29,Monitor Sem Fio,Eletrônicos,541.71,110,3.5
34,Notebook Ergonômico,Eletrônicos,589.19,467,2.9
35,Tablet Ultra HD,Eletrônicos,355.71,252,2.3
42,Câmera Portátil,Eletrônicos,626.27,400,1.8
46,Carregador Ergonômico,Eletrônicos,655.46,243,1.3

# ILOC

In [58]:
df_produtos.iloc[15]

Nome do Produto         Câmera Básico
Categoria do Produto    Áudio e Vídeo
Preço do Produto                45.56
Itens Vendidos                    140
Avaliação do Produto              4.7
Name: 15, dtype: object

In [59]:
df_produtos.iloc[1:16]

,Nome do Produto,Categoria do Produto,Preço do Produto,Itens Vendidos,Avaliação do Produto
1,Carregador Bluetooth,Eletrônicos,643.60,272,3.5
2,Roteador Ultra HD,Áudio e Vídeo,642.42,497,2.8
3,Caixa de Som Gaming,Áudio e Vídeo,260.88,356,3.0
4,Roteador Gaming,Periféricos,275.75,67,1.1
5,Desktop Compacto,Eletrônicos,100.58,157,1.8
6,Câmera Gaming,Eletrônicos,816.84,303,1.5
7,Microfone Ergonômico,Dispositivos Móveis,71.11,363,1.3
8,Mouse Portátil,Dispositivos Móveis,120.25,400,2.6
9,Impressora Ergonômico,Informática,978.15,490,4.6
10,Caixa de Som Ergonômico,Acessórios,985.30,325,2.6
11,Câmera Profissional,Eletrônicos,38.25,449,1.9
12,Desktop Premium,Acessórios,654.50,34,4.4
13,Carregador Profissional,Eletrônicos,758.30,81,3.3
14,Webcam Sem Fio,Eletrônicos,121.72,37,2.5
15,Câmera Básico,Áudio e Vídeo,45.56,140,4.7

In [60]:
# Cria um novo DataFrame definindo 'Nome do Produto' como índice
df_produtos_com_nome_indice = df_produtos.set_index('Nome do Produto')
df_produtos_com_nome_indice

,Categoria do Produto,Preço do Produto,Itens Vendidos,Avaliação do Produto
Nome do Produto,,,,
Carregador Ergonômico,Eletrônicos,729.33,277,2.7
Carregador Bluetooth,Eletrônicos,643.60,272,3.5
Roteador Ultra HD,Áudio e Vídeo,642.42,497,2.8
Caixa de Som Gaming,Áudio e Vídeo,260.88,356,3.0
Roteador Gaming,Periféricos,275.75,67,1.1
Desktop Compacto,Eletrônicos,100.58,157,1.8
Câmera Gaming,Eletrônicos,816.84,303,1.5
Microfone Ergonômico,Dispositivos Móveis,71.11,363,1.3
Mouse Portátil,Dispositivos Móveis,120.25,400,2.6
Impressora Ergonômico,Informática,978.15,490,4.6
Caixa de Som Ergonômico,Acessórios,985.30,325,2.6
Câmera Profissional,Eletrônicos,38.25,449,1.9
Desktop Premium,Acessórios,654.50,34,4.4
Carregador Profissional,Eletrônicos,758.30,81,3.3
Webcam Sem Fio,Eletrônicos,121.72,37,2.5
Câmera Básico,Áudio e Vídeo,45.56,140,4.7
Desktop Profissional,Informática,403.14,209,3.9
Câmera Gaming,Eletrônicos,995.41,242,2.2
Caixa de Som Premium,Eletrônicos,495.30,92,1.3
Caixa de Som Profissional,Eletrônicos,134.02,30,2.1
Teclado Bluetooth,Periféricos,570.69,378,3.3
Caixa de Som Básico,Áudio e Vídeo,783.90,482,3.1
Smartwatch Sem Fio,Áudio e Vídeo,841.62,354,2.8
Impressora Premium,Periféricos,437.98,70,1.5
Tablet Gaming,Informática,383.11,163,2.4
Caixa de Som Gaming,Eletrônicos,874.02,342,2.0
Desktop Gaming,Periféricos,157.81,13,1.2
Impressora Premium,Áudio e Vídeo,657.47,138,4.8
Webcam Gaming,Periféricos,595.93,293,3.3
Monitor Sem Fio,Eletrônicos,541.71,110,3.5
Câmera Básico,Áudio e Vídeo,955.11,425,3.7
Impressora Profissional,Dispositivos Móveis,402.02,440,4.9
Tablet Gaming,Acessórios,829.17,84,2.1
Caixa de Som Compacto,Informática,661.79,414,1.8
Notebook Ergonômico,Eletrônicos,589.19,467,2.9
Tablet Ultra HD,Eletrônicos,355.71,252,2.3
Fone de Ouvido Bluetooth,Áudio e Vídeo,113.46,189,2.8
Notebook Profissional,Informática,715.63,406,3.0
Mouse Gaming,Acessórios,511.85,60,2.6
Webcam Ultra HD,Informática,782.20,130,2.3
Impressora Compacto,Periféricos,67.84,50,4.6
Desktop Bluetooth,Periféricos,670.30,397,1.1
Câmera Portátil,Eletrônicos,626.27,400,1.8
Fone de Ouvido Gaming,Dispositivos Móveis,44.64,17,3.7
Câmera Bluetooth,Periféricos,365.15,23,4.4
Webcam Portátil,Acessórios,724.34,104,1.1
Carregador Ergonômico,Eletrônicos,655.46,243,1.3
Fone de Ouvido Compacto,Dispositivos Móveis,847.99,163,1.3
Monitor Premium,Dispositivos Móveis,420.77,115,1.5
Fone de Ouvido Básico,Dispositivos Móveis,303.53,487,2.7

In [62]:
df_produtos_com_nome_indice.loc["Fone de Ouvido Compacto"]

Categoria do Produto    Dispositivos Móveis
Preço do Produto                     847.99
Itens Vendidos                          163
Avaliação do Produto                    1.3
Name: Fone de Ouvido Compacto, dtype: object

In [63]:
df_produtos_com_nome_indice.loc["Fone de Ouvido Compacto", "Preço do Produto"]

np.float64(847.99)

In [64]:
df_produtos_com_nome_indice.loc[["Fone de Ouvido Compacto", "Carregador Ergonômico"], ["Preço do Produto", "Avaliação do Produto"]]

                         Preço do Produto  Avaliação do Produto
Nome do Produto
Fone de Ouvido Compacto            847.99                   1.3
Carregador Ergonômico              729.33                   2.7
Carregador Ergonômico              655.46                   1.3

In [68]:
eletronicos = df_produtos_com_nome_indice[df_produtos_com_nome_indice["Categoria do Produto"] == "Eletrônicos"]
df_produtos_com_nome_indice.loc[eletronicos.index, ["Preço do Produto","Itens Vendidos"]]

                           Preço do Produto  Itens Vendidos
Nome do Produto
Carregador Ergonômico                729.33             277
Carregador Ergonômico                655.46             243
Carregador Bluetooth                 643.60             272
Desktop Compacto                     100.58             157
Câmera Gaming                        816.84             303
Câmera Gaming                        995.41             242
Câmera Profissional                   38.25             449
Carregador Profissional              758.30              81
Webcam Sem Fio                       121.72              37
Câmera Gaming                        816.84             303
Câmera Gaming                        995.41             242
Caixa de Som Premium                 495.30              92
Caixa de Som Profissional            134.02              30
Caixa de Som Gaming                  260.88             356
Caixa de Som Gaming                  874.02             342
Monitor Sem Fio                      541.71             110
Notebook Ergonômico                  589.19             467
Tablet Ultra HD                      355.71             252
Câmera Portátil                      626.27             400
Carregador Ergonômico                729.33             277
Carregador Ergonômico                655.46             243

In [72]:
perifericos = df_produtos_com_nome_indice[df_produtos_com_nome_indice["Categoria do Produto"] == "Periféricos"]
df_produtos_com_nome_indice.loc[perifericos.index, ["Categoria do Produto"]] = "Acessórios"
df_produtos_com_nome_indice

,Categoria do Produto,Preço do Produto,Itens Vendidos,Avaliação do Produto
Nome do Produto,,,,
Carregador Ergonômico,Eletrônicos,729.33,277,2.7
Carregador Bluetooth,Eletrônicos,643.60,272,3.5
Roteador Ultra HD,Áudio e Vídeo,642.42,497,2.8
Caixa de Som Gaming,Áudio e Vídeo,260.88,356,3.0
Roteador Gaming,Acessórios,275.75,67,1.1
Desktop Compacto,Eletrônicos,100.58,157,1.8
Câmera Gaming,Eletrônicos,816.84,303,1.5
Microfone Ergonômico,Dispositivos Móveis,71.11,363,1.3
Mouse Portátil,Dispositivos Móveis,120.25,400,2.6
Impressora Ergonômico,Informática,978.15,490,4.6
Caixa de Som Ergonômico,Acessórios,985.30,325,2.6
Câmera Profissional,Eletrônicos,38.25,449,1.9
Desktop Premium,Acessórios,654.50,34,4.4
Carregador Profissional,Eletrônicos,758.30,81,3.3
Webcam Sem Fio,Eletrônicos,121.72,37,2.5
Câmera Básico,Áudio e Vídeo,45.56,140,4.7
Desktop Profissional,Informática,403.14,209,3.9
Câmera Gaming,Eletrônicos,995.41,242,2.2
Caixa de Som Premium,Eletrônicos,495.30,92,1.3
Caixa de Som Profissional,Eletrônicos,134.02,30,2.1
Teclado Bluetooth,Acessórios,570.69,378,3.3
Caixa de Som Básico,Áudio e Vídeo,783.90,482,3.1
Smartwatch Sem Fio,Áudio e Vídeo,841.62,354,2.8
Impressora Premium,Acessórios,437.98,70,1.5
Tablet Gaming,Informática,383.11,163,2.4
Caixa de Som Gaming,Eletrônicos,874.02,342,2.0
Desktop Gaming,Acessórios,157.81,13,1.2
Impressora Premium,Acessórios,657.47,138,4.8
Webcam Gaming,Acessórios,595.93,293,3.3
Monitor Sem Fio,Eletrônicos,541.71,110,3.5
Câmera Básico,Áudio e Vídeo,955.11,425,3.7
Impressora Profissional,Dispositivos Móveis,402.02,440,4.9
Tablet Gaming,Acessórios,829.17,84,2.1
Caixa de Som Compacto,Informática,661.79,414,1.8
Notebook Ergonômico,Eletrônicos,589.19,467,2.9
Tablet Ultra HD,Eletrônicos,355.71,252,2.3
Fone de Ouvido Bluetooth,Áudio e Vídeo,113.46,189,2.8
Notebook Profissional,Informática,715.63,406,3.0
Mouse Gaming,Acessórios,511.85,60,2.6
Webcam Ultra HD,Informática,782.20,130,2.3
Impressora Compacto,Acessórios,67.84,50,4.6
Desktop Bluetooth,Acessórios,670.30,397,1.1
Câmera Portátil,Eletrônicos,626.27,400,1.8
Fone de Ouvido Gaming,Dispositivos Móveis,44.64,17,3.7
Câmera Bluetooth,Acessórios,365.15,23,4.4
Webcam Portátil,Acessórios,724.34,104,1.1
Carregador Ergonômico,Eletrônicos,655.46,243,1.3
Fone de Ouvido Compacto,Dispositivos Móveis,847.99,163,1.3
Monitor Premium,Dispositivos Móveis,420.77,115,1.5
Fone de Ouvido Básico,Dispositivos Móveis,303.53,487,2.7

In [74]:
df_produtos_com_nome_indice['Categoria do Produto'].unique()

array(['Eletrônicos', 'Áudio e Vídeo', 'Acessórios',
       'Dispositivos Móveis', 'Informática'], dtype=object)